import { Posts, Comment } from "./types";

export const samplePosts: Posts[] = [
    {
        id: "1",
        name: "Alice",
        statusCount: 3,
        viewed: 3,
        notViewed: 0,
        link: "1", // Parent link
        recentStatus: [
            {
                id: "1",
                type: "text",
                statusText: "klshdajsvdgjasdgahsdgahsdfahsdfahsdgahfs!",
                bgColor: "red",
                path: null,
                // 5 minutes ago relative to 17 Feb 2025 17:03
                timestamp: "2025-02-17T16:58:00Z",
                views: 120,
                comments: 5,
                shares: 2,
            },
            {
                id: "2",
                type: "text",
                statusText: "Had an amazing time at the park!",
                bgColor: "blue",
                path: null,
                // 45 minutes ago relative to 17 Feb 2025 17:03
                timestamp: "2025-02-17T16:18:00Z",
                views: 200,
                comments: 12,
                shares: 6,
            },
            {
                id: "3",
                type: "text",
                statusText: "Feeling productive today!",
                bgColor: "green",
                path: null,
                // 1 hour ago relative to 17 Feb 2025 17:03
                timestamp: "2025-02-17T15:58:00Z",
                views: 85,
                comments: 3,
                shares: 1,
            },
        ],
    },
    {
        id: "2",
        name: "Bob",
        statusCount: 2,
        viewed: 1,
        notViewed: 1,
        link: "2", // Parent link
        recentStatus: [
            {
                id: "4",
                type: "video",
                statusText: "Check out this new video!",
                path: "/assets/images/video.mp4",
                bgColor: null,
                // 13 minutes ago relative to 17 Feb 2025 17:03
                timestamp: "2025-02-17T16:50:00Z",
                views: 150,
                comments: 8,
                shares: 4,
            },
            {
                id: "5",
                type: "video",
                statusText: "My favorite video of the day!",
                path: "/assets/images/short.mp4",
                bgColor: null,
                // 53 minutes ago relative to 17 Feb 2025 17:03
                timestamp: "2025-02-17T16:10:00Z",
                views: 220,
                comments: 15,
                shares: 10,
            },
        ],
    },
    {
        id: "3",
        name: "Charlie",
        statusCount: 50,
        viewed: 25,
        notViewed: 30,
        link: "3", // Parent link
        recentStatus: [
            {
                id: "6",
                type: "image",
                statusText: "New photo update!",
                path: "/assets/images/pic.jpeg",
                bgColor: null,
                // 23 minutes ago relative to 17 Feb 2025 17:03
                timestamp: "2025-02-17T16:40:00Z",
                views: 500,
                comments: 25,
                shares: 15,
            },
            {
                id: "7",
                type: "image",
                statusText: "Had a great weekend!",
                path: "/assets/images/pic.jpeg",
                bgColor: null,
                // 33 minutes ago relative to 17 Feb 2025 17:03
                timestamp: "2025-02-17T16:30:00Z",
                views: 350,
                comments: 18,
                shares: 12,
            },
            {
                id: "8",
                type: "image",
                statusText: "My dog just got a new toy!",
                path: "/assets/images/pic.jpeg",
                bgColor: null,
                // 1 hour ago relative to 17 Feb 2025 17:03
                timestamp: "2025-02-17T15:58:00Z",
                views: 430,
                comments: 22,
                shares: 9,
            },
        ],
    },
    {
        id: "4",
        name: "David",
        statusCount: 1,
        viewed: 1,
        notViewed: 0,
        link: "4", // Parent link
        recentStatus: [
            {
                id: "9",
                type: "text",
                statusText: "Just had a great lunch.",
                bgColor: "bg-red-100",
                path: null,
                // 33 minutes ago relative to 17 Feb 2025 17:03
                timestamp: "2025-02-17T16:30:00Z",
                views: 95,
                comments: 4,
                shares: 3,
            },
            {
                id: "10",
                type: "text",
                statusText: "I love a good cup of coffee!",
                bgColor: "bg-yellow-100",
                path: null,
                // 1 hour ago relative to 17 Feb 2025 17:03
                timestamp: "2025-02-17T15:58:00Z",
                views: 120,
                comments: 6,
                shares: 5,
            },
        ],
    },
];

export const comments: Comment[] = [
    {
        id: "1",
        username: "gloria",
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        timestamp: "2024-03-06T14:30:00Z",
        avatar: "https://i.pravatar.cc/40?img=10",
        likes: 10,
        replies: [
            {
                id: "101",
                username: "john_doe",
                reply_username: "gloria",
                likes: 5,
                text: "I totally agree with you! This is insightful.",
                avatar: "https://i.pravatar.cc/40?img=10",
                timestamp: "2024-03-06T16:00:00Z",
            },
        ],
        post: "8348756345",
        post_type: "public"
    },
    {
        id: "2",
        username: "alex",
        text: "Great discussion! I found this really helpful.",
        timestamp: "2024-03-05T10:15:00Z",
        avatar: "https://i.pravatar.cc/40?img=20",
        likes: 8,
        replies: [
            {
                id: "102",
                username: "maria",
                reply_username: "alex",
                likes: 3,
                text: "Absolutely! Thanks for sharing your thoughts.",
                avatar: "https://i.pravatar.cc/40?img=10",
                timestamp: "2024-03-05T12:45:00Z",
            },
        ],
        post: "8345ghj34g5",
        post_type: "public"
    },
];

export const sampleMyPosts: Posts = {
    id: "1",
    name: "Alice",
    statusCount: 3,
    viewed: 3,
    notViewed: 0,
    link: "1",
    recentStatus: [
        {
            id: "1",
            type: "text",
            statusText: "Hell yeah!",
            bgColor: "red",
            path: null,
            timestamp: "2025-02-17T16:58:00Z",
            views: 120,
            comments: 5,
            shares: 2,
        },
        {
            id: "2",
            type: "text",
            statusText: "Had an amazing time at the park!",
            bgColor: "blue",
            path: null,
            timestamp: "2025-02-17T16:18:00Z",
            views: 200,
            comments: 12,
            shares: 6,
        },
        {
            id: "3",
            type: "text",
            statusText: "Feeling productive today!",
            bgColor: "green",
            path: null,
            timestamp: "2025-02-17T15:58:00Z",
            views: 85,
            comments: 3,
            shares: 1,
        },
    ],
};

export const messages = [
    {
        id: '1',
        name: "John Doe",
        replyID: null,
        isReply: false,
        text: "Hi there! How are you?",
        time: "12:45 PM",
        type: "incoming",
        file: 'assets/images/pic.jpeg',
        filetype: 'PNG',
        fileName: 'my pic',
        isFile: true,
        fileSize: '1.76MB',
        color: "red-500",
    },
    {
        id: '2',
        name: "You",
        replyID: null,
        isReply: false,
        text: "Hello! I'm good, thank you. And you?",
        time: "10:45 AM",
        type: "outgoing",
        file: '',
        filetype: '',
        fileName: '',
        isFile: false,
        fileSize: '',
        color: "red-500",
    },
    {
        id: '3',
        name: "John Doe",
        replyID: null,
        isReply: false,
        text: "I'm doing well too. Let's catch up soon!",
        time: "12:45 PM",
        type: "incoming",
        file: '',
        filetype: '',
        fileName: '',
        isFile: false,
        fileSize: '',
        color: "red-500",
    },
    {
        id: '4',
        name: "You",
        replyID: null,
        isReply: false,
        text: "Sure, let's plan for the weekend.",
        time: "12:45 PM",
        type: "outgoing",
        file: '',
        filetype: '',
        fileName: '',
        isFile: false,
        fileSize: '',
        color: "red-500",
    },
    {
        id: '5',
        name: "John Doe",
        replyID: null,
        isReply: false,
        text: "Hey there, I wanted to share some detailed updates regarding our project. Recently, I've been analyzing market trends, and it's fascinating to see how rapidly technology is transforming industries. We are witnessing a shift towards digital-first strategies where user experience and accessibility are paramount. The integration of artificial intelligence and machine learning into everyday processes is not only optimizing operations but also unlocking new potentials for innovation. I believe that by embracing these changes, we can create solutions that are not only efficient but also genuinely impactful in improving people's lives. Looking forward to discussing these insights further and exploring how we can leverage these trends to drive our business forward. Have a great day!",
        time: "1:00 PM",
        type: "incoming",
        file: '',
        filetype: '',
        fileName: '',
        isFile: false,
        fileSize: '',
        color: "red-500",
    },
    {
        id: '6',
        name: "John Doe",
        replyID: "5",
        isReply: true,
        text: "Really!",
        time: "1:02 PM",
        type: "outgoing",
        file: '',
        filetype: '',
        fileName: '',
        isFile: false,
        fileSize: '',
        color: "red-500",
        replyMessage: {
            id: '5',
            name: "John Doe",
            text: "Hey there, I wanted to share some detailed updates regarding our project. Recently, I've been analyzing market trends, and it's fascinating to see how rapidly technology is transforming industries. We are witnessing a shift towards digital-first strategies where user experience and accessibility are paramount. The integration of artificial intelligence and machine learning into everyday processes is not only optimizing operations but also unlocking new potentials for innovation. I believe that by embracing these changes, we can create solutions that are not only efficient but also genuinely impactful in improving people's lives. Looking forward to discussing these insights further and exploring how we can leverage these trends to drive our business forward. Have a great day!",
            time: "1:00 PM",
            file: '',
            filetype: '',
            fileName: '',
            isFile: false,
            fileSize: '',
            color: "red-500",
        },
    },
    {
        id: '7',
        name: "John Doe",
        replyID: "6",
        isReply: true,
        text: "Hey there, I wanted to share some detailed updates regarding our project. Recently, I've been analyzing market trends, and it's fascinating to see how rapidly technology is transforming industries. We are witnessing a shift towards digital-first strategies where user experience and accessibility are paramount. The integration of artificial intelligence and machine learning into everyday processes is not only optimizing operations but also unlocking new potentials for innovation. I believe that by embracing these changes, we can create solutions that are not only efficient but also genuinely impactful in improving people's lives. Looking forward to discussing these insights further and exploring how we can leverage these trends to drive our business forward. Have a great day!",
        time: "1:05 PM",
        type: "incoming",
        file: '',
        filetype: '',
        fileName: '',
        isFile: false,
        fileSize: '',
        color: "red-500",
        replyMessage: {
            id: '6',
            name: "John Doe",
            text: "Really!",
            time: "1:02 PM",
            file: '',
            filetype: '',
            fileName: '',
            isFile: false,
            fileSize: '',
            color: "red-500",
        },
    },
];

export const viewers = [
    { id: 1, name: "John Doe", time: "2 minutes" },
    { id: 2, name: "Jane Smith", time: "10 minutes" },
    { id: 3, name: "Michael Johnson", time: "23 minutes" },
    { id: 4, name: "Emily Davis", time: "30 minutes" },
    { id: 5, name: "Chris Brown", time: "35 minutes" },
    { id: 6, name: "Sophia Lee", time: "40 minutes" },
    { id: 7, name: "Daniel White", time: "50 minutes" },
    { id: 8, name: "Olivia Green", time: "55 minutes" },
];

export const groupmessages = [
    {
        id: '1',
        name: "John Doe",
        replyID: null,
        isReply: false,
        color: "red-500",
        text: "Hi there! How are you, Check out https://example.com and https://google.com for details!?",
        time: "12:45 PM",
        type: "incoming",
        file: '',
        filetype: '',
        fileName: '',
        isFile: false,
        fileSize: '',
    },
    {
        id: '2',
        name: "Njoro mugithi",
        replyID: null,
        isReply: false,
        color: "blue-500",
        text: "Hello! I'm good, thank you. And you Check out https://example.com ?",
        time: "10:45 AM",
        type: "outgoing",
        file: 'assets/images/pic.jpeg',
        filetype: 'PNG',
        fileName: 'my pic',
        isFile: true,
        fileSize: '1.76MB',
    },
    {
        id: '3',
        name: "John Doe",
        replyID: null,
        isReply: false,
        color: "green-500",
        text: "I'm doing well too. Let's catch up soon!",
        time: "12:45 PM",
        type: "incoming",
        file: 'audio/song.mp3',
        filetype: 'MP3',
        fileName: 'Audio MP3',
        isFile: true,
        fileSize: '244KB',
    },
    {
        id: '4',
        name: "Njoro mugithi",
        replyID: null,
        isReply: false,
        color: "yellow-500",
        text: "Sure, let's plan for the weekend.",
        time: "12:55 PM",
        type: "incoming",
        fileName: 'Math 425 pdf',
        file: 'assets/files/file.pdf',
        filetype: 'PDF',
        isFile: true,
        fileSize: '3.56MB',
    },
    {
        id: '5',
        name: "John Doe",
        replyID: null,
        isReply: false,
        color: "yellow-500",
        text: "Hey there, I wanted to share some detailed updates regarding our project. Recently, I've been analyzing market trends, and it's fascinating to see how rapidly technology is transforming industries. We are witnessing a shift towards digital-first strategies where user experience and accessibility are paramount. The integration of artificial intelligence and machine learning into everyday processes is not only optimizing operations but also unlocking new potentials for innovation. I believe that by embracing these changes, we can create solutions that are not only efficient but also genuinely impactful in improving people's lives. Looking forward to discussing these insights further and exploring how we can leverage these trends to drive our business forward. Have a great day!",
        time: "1:00 PM",
        type: "incoming",
        fileName: 'Man vs Chelsea game',
        file: 'assets/images/video.mp4',
        filetype: 'MP4',
        isFile: true,
        fileSize: '10.25MB',
    },
    {
        id: '6',
        name: "John Doe",
        replyID: "5",
        isReply: true,
        color: "purple-500",
        text: "Here is the file for the project!",
        time: "1:02 PM",
        type: "incoming",
        fileName: 'Project image',
        file: 'assets/images/pic.jpeg',
        filetype: 'JPEG',
        fileSize: '2.03MB',
        isFile: true,
        replyMessage: {
            id: '5',
            name: "John Doe",
            text: "Hey there, I wanted to share some detailed updates regarding our project. Recently, I've been analyzing market trends, and it's fascinating to see how rapidly technology is transforming industries. We are witnessing a shift towards digital-first strategies where user experience and accessibility are paramount. The integration of artificial intelligence and machine learning into everyday processes is not only optimizing operations but also unlocking new potentials for innovation. I believe that by embracing these changes, we can create solutions that are not only efficient but also genuinely impactful in improving people's lives. Looking forward to discussing these insights further and exploring how we can leverage these trends to drive our business forward. Have a great day!",
            time: "1:00 PM",
            color: "yellow-500",
            file: '',
            filetype: '',
            isFile: false,
            fileName: '',
            fileSize: '',
        },
    },
    {
        id: '7',
        name: "John Doe",
        replyID: "6",
        isReply: true,
        color: "green-500",
        text: "Hey there, I wanted to share some detailed updates regarding our project. Recently, I've been analyzing market trends, and it's fascinating to see how rapidly technology is transforming industries. We are witnessing a shift towards digital-first strategies where user experience and accessibility are paramount. The integration of artificial intelligence and machine learning into everyday processes is not only optimizing operations but also unlocking new potentials for innovation. I believe that by embracing these changes, we can create solutions that are not only efficient but also genuinely impactful in improving people's lives. Looking forward to discussing these insights further and exploring how we can leverage these trends to drive our business forward. Have a great day!",
        time: "1:05 PM",
        type: "incoming",
        file: '',
        filetype: '',
        isFile: false,
        fileSize: '',
        fileName: '',
        replyMessage: {
            id: '6',
            name: "John Doe",
            text: "Really!",
            time: "1:02 PM",
            color: "blue-500",
            fileName: '',
            file: '',
            filetype: '',
            isFile: false,
            fileSize: '',
        },
    },
];

export const chats = [
    {
        name: "John Doe",
        profilePic: "/assets/images/profile-bg.png",
        last_message: "Hello",
        last_sender: true,
        last_timestamp: new Date().toISOString(),
        status: "read"
    },
    {
        name: "Jane Smith",
        profilePic: "/assets/images/profile-bg.png",
        last_message: "Hey, how are you?",
        last_sender: false,
        last_timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
        status: "delivered"
    },
    {
        name: "Michael Johnson",
        profilePic: "/assets/images/profile-bg.png",
        last_message: "See you later!",
        last_sender: true,
        last_timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        status: "not-delivered"
    },
];

export const groups = [
    {
        name: "Mabanzenga Nation",
        profilePic: "/assets/images/group-profile-3.png",
        last_message: "Hello",
        last_sender: true,
        last_timestamp: new Date().toISOString(),
        status: "read",
        last_sender_name: "Kidongo Mdogo"
    },
    {
        name: "Football Nation",
        profilePic: "/assets/images/group-profile-3.png",
        last_message: "Hey, how are you?",
        last_sender: false,
        last_timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
        status: "delivered",
        last_sender_name: "Mzima mzima"
    },
    {
        name: "Uoe Nation",
        profilePic: "/assets/images/group-profile-3.png",
        last_message: "See you later!",
        last_sender: true,
        last_timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        status: "not-delivered",
        last_sender_name: "Wawele kiwele"
    },
];